language: go

go: 1.7.4

install:
 - go version
 - repo_dir=$(/bin/pwd -P)
 - go get -d -u -v ./...
 - go test -i
 - make install
 - ${GOPATH%%:*}/bin/sks_stats_daemon -version

script:
 - go vet
 - go test -v
